on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
jobs:
  lint:
    name: Lint with PHP_CodeSniffer
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Install composer dependencies
        run: composer install
      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs
